services:
  todo-app:
    build:
      context: .
    container_name: todo-app
    ports:
      - "2020:3030"
    networks:
      - todo-network
    
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - todo-network
    volumes:
      - todoapp-data:/data/db

networks:
  todo-network:
volumes:
  todoapp-data:

